filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'app/views/*'
        - 'app/config/*'
        - 'app/database/*'
        - 'vendor/*'

before_commands:
    - 'composer install --dev --prefer-source'

checks:
    php: {  }

tools:
    external_code_coverage:
        timeout: 900
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]

coding_style:
    php:
        braces:
            if:
                else_on_new_line: true
